### ISSUE TITLE
CVE API throws HTTP 410 Error

### ISSUE THREAD

**Issue by salmansalman** [hsainnos/macDetec#1]
Line 67 of dl_database.py throws a HTTP 410 error because the url http://cve.circl.lu/api/search/ is no longer a publicly searchable API and they recommend instead to use the local version found at https://github.com/cve-search/cve-search

**Comment by mniedermaier** [comment]
Thank you for the hint. I have added instruction to use the docker-compose container provided by cve-details in the 1e39f3e commit. Please have a look.

**Comment by salmansalman** [comment]
Works great now, thanks for updating

**Comment by mniedermaier** [comment]
No problem. Thanks for your response :+1:
